#lang racket/base
(require racket/class
         racket/draw)

(provide (all-defined-out))

(define brown (make-color 182 100 76))

(define (brighter-color c s)
  (define (brighter n) (- 255 (quotient (- 255 n) s)))
  (let ([c (if (string? c)
               (send the-color-database find-color c)
               c)])
    (make-color (brighter (send c red))
                (brighter (send c green))
                (brighter (send c blue)))))

(define (darker-color c s)
  (define (darker n) (inexact->exact (round (* n s))))
  (make-color (darker (send c red))
              (darker (send c green))
              (darker (send c blue))))

(define no-brush (make-brush #:style 'transparent))
(define white-brush (make-brush #:color "white"))
(define black-brush (make-brush #:color "black"))
(define red-brush (make-brush #:color "red"))
(define gray-brush (make-brush #:color "gray"))
(define dark-gray-brush (make-brush #:color "darkgray"))
(define pink-brush (make-brush #:color "pink"))
(define semi-white-brush (make-brush #:color (make-color 255 255 255 0.5)))
(define brown-brush (make-brush #:color brown))
(define tan-brush (make-brush #:color "tan"))
(define med-brown-brush tan-brush #;(make-brush #:color "darkgoldenrod"))
(define peach-brush (make-brush #:color "peachpuff"))
(define cartoon-brush (make-brush #:color "peru"))
(define light-brown-brush (make-brush #:color (brighter-color brown 2)))
(define red-brown-brush (make-brush #:color (make-color 240 100 76)))
(define gold-brush (make-brush #:color "gold"))
(define yellow-brush (make-brush #:color "yellow"))
(define blue-brush (make-brush #:color "lightblue"))
(define bluer-brush (make-brush #:color "blue"))
(define denim-brush (make-brush #:color "cornflowerblue"))
(define green-brush (make-brush #:color "lightgreen"))
(define olive-brush (make-brush #:color "olivedrab"))
(define khaki-brush (make-brush #:color "khaki"))
(define med-blue-brush (make-brush #:color "royalblue"))
(define dark-blue-brush (make-brush #:color "darkblue"))
(define maroon-brush (make-brush #:color "maroon"))
(define orange-brush (make-brush #:color "orange"))
(define purple-brush (make-brush #:color "purple"))
(define almost-black-brush (make-brush #:color (make-color 50 50 50)))
(define lightest-tan-brush (make-brush #:color "NavajoWhite"))
(define light-tan-brush (make-brush #:color "Burlywood"))

(define white-pen (make-pen #:color "white" #:width 1))
(define black-pen (make-pen #:width 1))
(define brown-pen (make-pen #:color "brown"))
(define yellow-pen (make-pen #:color "yellow"))
(define no-pen (make-pen #:style 'transparent))
(define gray-pen (make-pen #:color "gray" #:width 2))
(define gray-thin-pen (make-pen #:color "gray"))
(define dark-gray-pen (make-pen #:color (make-color 80 80 80)))
(define dark-gray-thin-pen (make-pen #:color (make-color 80 80 80) #:width 0.25))
(define almost-black-pen (make-pen #:color (make-color 40 40 40)))
(define semi-white-pen (make-pen #:color (make-color 150 150 150 0.5) #:width 1))
(define thick-black-pen (make-pen #:width 2))
(define fat-black-pen (make-pen #:width 20))
(define fat-brown-pen (make-pen #:width 20 #:color "brown"))
